### ISSUE TITLE
segfault when litterbox is down

### ISSUE THREAD

**Issue by brw** [Arno500/plex-richpresence#22]
Compared with litterbox being down and then up again later. Pretty sure it's just that. Also happens if it times out.
```
Jun 09 20:15:23 bamibal sh[38577]: 2024/06/09 20:15:23 Error uploading image to litterbox:  Post "https://litterbox.catbox.moe/resources/internals/api.php": dial tcp 108.181.20.36:443: connect: connection refused
Jun 09 20:15:23 bamibal sh[38577]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 09 20:15:23 bamibal sh[38577]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x519113]
Jun 09 20:15:23 bamibal sh[38577]: goroutine 114 [running]:
Jun 09 20:15:23 bamibal sh[38577]: bytes.(*Buffer).WriteTo(0xc0005b8120, {0x0?, 0x0?})
Jun 09 20:15:23 bamibal sh[38577]:         /home/bas/.local/share/mise/installs/go/1.22.3/src/bytes/buffer.go:261 +0x53
Jun 09 20:15:23 bamibal sh[38577]: io.copyBuffer({0x0, 0x0}, {0xf8fca0, 0xc0005b8120}, {0x0, 0x0, 0x0})
Jun 09 20:15:23 bamibal sh[38577]:         /home/bas/.local/share/mise/installs/go/1.22.3/src/io/io.go:411 +0x9d
Jun 09 20:15:23 bamibal sh[38577]: io.Copy(...)
Jun 09 20:15:23 bamibal sh[38577]:         /home/bas/.local/share/mise/installs/go/1.22.3/src/io/io.go:388
Jun 09 20:15:23 bamibal sh[38577]: gitlab.com/Arno500/plex-richpresence/discord.createMultipartForm.func1()
Jun 09 20:15:23 bamibal sh[38577]:         /home/bas/dev/plex-richpresence/discord/file-hosting.go:48 +0x1e5
Jun 09 20:15:23 bamibal sh[38577]: created by gitlab.com/Arno500/plex-richpresence/discord.createMultipartForm in goroutine 85
Jun 09 20:15:23 bamibal sh[38577]:         /home/bas/dev/plex-richpresence/discord/file-hosting.go:35 +0x1ea
Jun 09 20:15:23 bamibal systemd[654]: plex-rich-presence.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 09 20:15:23 bamibal systemd[654]: plex-rich-presence.service: Failed with result 'exit-code'.
```

**Comment by Arno500** [comment]
Hello @brw!
Thanks for the report!

I was not properly managing the errors if the request was failing. This should be fixed and shipped in 1.10.4, updating automatically in the next 12 hours (or if you download it manually).

I will close this ticket, but please don't hesitate to reopen it if you still see the issue on your side.

Best,
Arno
